name: bili
services:
    bili:
        container_name: bili
        volumes:
            - ./cookies.txt:/cookies.txt
            - .list.txt:/list.txt
            - ./videos:/data
        image: zhangyiming748/bili
# docker run -it --name ytdlp -v ./cookies.txt:/cookies.txt zhangyiming748/ytdlp ash